"""empty message

Revision ID: 30d8eaa8745e
Revises: d6512f3fb0b6
Create Date: 2022-12-29 02:25:18.064976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30d8eaa8745e'
down_revision = 'd6512f3fb0b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmark', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
